cms/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [		#empty list
	#/
	url( r'^$', views.list_of_posts, name = 'list_of_posts' ),
	url( r'^(?P<slug>[-\w]+)/$', views.post_detail, name = "post_detail" ),
	url( r'^category/(?P<category_slug>[-\w]+)/$', views.list_of_posts_by_category, name = 'list_of_posts_by_category' ),
	url( r'^(?P<slug>[-w\w]+)/comment/$', views.add_comment, name = 'add_comment' ),
	url( r'^backend/post/new/$', views.new_post, name = 'new_post'  ),
	url( r'^backend/post/$', views.list_of_posts_backend, name = 'list_of_posts_backend'  ),
	url( r'^backend/post/(?P<slug>[-\w]+)/edit/$', views.edit_post, name= 'edit_post'),
	url( r'^backend/post/(?P<slug>[-\w]+)/delete/$', views.delete_post, name='delete_post' )
] 
#r means its a raw string

cms/cms/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url( r'^blog/', include( 'blog.urls', namespace = 'blog', app_name = 'blog' ) )
]

cms/blog/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

#Category
class Category( models.Model ):
	name = models.CharField( max_length = 250 )
	slug = models.SlugField( max_length = 250, unique = True )

	class Meta:
		ordering = ( 'name', )
		verbose_name = 'category'
		verbose_name_plural = 'categories'

	def get_absolute_url( self ):
		return reverse( 'blog:list_of_posts_by_category', args = [ self.slug ] )

	def __str__( self ):
		return self.name

#Post
class Post( models.Model ):
	STATUS_CHOICES = (
		( 'draft', 'Draft' ),
		( 'published', 'Published' ),
	)
	category = models.ForeignKey( Category )
	title = models.CharField( max_length = 250 )
	slug = models.SlugField( max_length = 250, unique = True )
	content = models.TextField()
	seo_title = models.CharField( max_length = 250 )
	seo_description = models.CharField( max_length = 160 )
	author = models.ForeignKey( User, related_name = 'blog_posts' )
	published = models.DateTimeField( default = timezone.now )
	created = models.DateTimeField( auto_now_add = True )
	updated = models.DateTimeField( auto_now = True )
	status = models.CharField( max_length = 9, choices = STATUS_CHOICES, default = 'draft' )

	def save( self, *args, **kwargs ):
		self.slug = slugify( self.title )
		super( Post, self ).save( *args, **kwargs )


	def get_absolute_url( self ):
		return reverse( 'blog:post_detail', args = [self.slug] )


	def __str__( self ):
		return self.title #title to be seen on the admin

class Comment( models.Model ):
	post = models.ForeignKey( Post, related_name = 'comments' )
	user = models.CharField( max_length = 250 )
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField( auto_now_add = True )
	approved = models.BooleanField( default = False )

	def approved( self ):
		self.approved = True
		self.save()

	def __str__( self ):
		return self.user

cms/blog/forms.py
from django import forms
from .models import Comment, Post

class CommentForm( forms.ModelForm ):
	class Meta:
		model = Comment
		fields = ( 'user', 'email', 'body' )

class PostForm( forms.ModelForm ):
	class Meta:
		model = Post
		fields = ( 'title',  'content', 'category', 'seo_title', 'seo_description', 'status' )

			

cms/blog/views.py
#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404
from django.contrib import messages
from .models import Post, Category, Comment
from .forms import CommentForm, PostForm
# Create your views here.

def list_of_posts_by_category( request, category_slug ):
	categories = Category.objects.all()
	post = Post.objects.filter( status = 'published' )
	if category_slug:
		category = get_object_or_404( Category, slug = category_slug )
		post = post.filter( category = category )
	template = 'blog/category/list_of_posts_by_category.html'
	context = { 'categories' : categories, 'post' : post, 'category' : category }
	return render( request, template, context )
 

def list_of_posts( request ):
	post = Post.objects.filter( status = 'published' )
	paginator = Paginator( post, 1)
	page = request.GET.get( 'page' )
	try:
		posts = paginator.page( page )
	except PageNotAnInteger:
		posts = paginator.page( 1 )
	except EmptyPage:
		posts = paginator.page( paginator.num_pages )

	template = 'blog/post/list_of_posts.html'
	context = { 'posts' : posts, 'page' : page }
	return render( request, template, context )


def post_detail( request, slug ):
	post = get_object_or_404( Post, slug = slug )
	context = { 'post' : post }
	if post.status == 'published':
		template = 'blog/post/post_detail.html'
		return render( request, template, context )
	else:
		template = 'blog/post/post_preview.html'	
		return render( request, template, context )

def add_comment( request, slug ):
	post = get_object_or_404( Post, slug = slug )
	if request.method == 'POST':
		form = CommentForm( request.POST )
		if form.is_valid():
			comment = form.save( commit = False )
			comment.post = post
			comment.save()
			return redirect( 'blog:post_detail', slug = post.slug )
	else:
		form = CommentForm()
	template = 'blog/post/add_comment.html'
	context = { 'form' : form }
	return render( request, template, context )

##############################
		# BACKEND
##############################

def new_post( request ):
	if request.method == 'POST':
		form = PostForm( request.POST )
		if form.is_valid():
			post = form.save( commit=False)
			post.author = request.user
			post.save()
			return redirect( 'blog:post_detail', slug=post.slug )
	else:
		form =PostForm()
	template = 'blog/backend/new_post.html'
	context = { 'form' : form }
	return render( request, template, context )

def list_of_posts_backend( request ):
	post = Post.objects.all()
	paginator = Paginator( post, 4)
	page = request.GET.get( 'page' )
	try:
		posts = paginator.page( page )
	except PageNotAnInteger:
		posts = paginator.page( 1 )
	except EmptyPage:
		posts = paginator.page( paginator.num_pages )

	template = 'blog/backend/list_of_posts_backend.html'
	context = { 'posts' : posts, 'page' : page }
	return render( request, template, context )

def edit_post( request, slug ):
	post = get_object_or_404( Post, slug = slug )
	if request.method == 'POST':
		form = PostForm( request.POST, instance=post )
		if form.is_valid():
			post = form.save( commit=False )
			post.author = request.user
			post.save()
			return redirect( 'blog:list_of_posts_backend' )
	else:
		form = PostForm( instance=post )
	template = 'blog/backend/new_post.html'
	context = { 'form' : form }
	return render( request, template, context )


def delete_post( request, slug ):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	post = get_object_or_404( Post, slug = slug )
	post.delete()
	messages.success( request, "Successfully Deleted" )
	return redirect( 'blog:list_of_posts_backend' )

cms/blog/templates/blog/backend/list_of_posts_backend.html
{% extends 'blog/base.html' %}

{% block title %} {{ category.name }} {% endblock %}

{% block content %}

	<div class="table-responsive">
		<h1>A List of your posts</h1>
		<table class="table table-hover table-condensed">
			<tr>
				<th>Title</th>
				<th>Slug</th>
				<th>Author</th>
				<th>Published</th>
				<th>status</th>
				<th>Edit post</th>
				<th>Delete</th>
			</tr>
			{% for post in posts %}
				{% if post.status == 'draft' %}
				<tr class="danger">
					{% else %}
					<tr>
					{% endif %}				
						<td>{{ post.title }}</td>
						<td>{{ post.slug }}</td>
						<td>{{ post.author }}</td>
						<td>{{ post.published }}</td>
						<td>{{ post.status }}</td>
						<td><a href="{% url 'blog:edit_post' slug=post.slug %}"><button type="button" class="btn btn-default"><span class="glyphicon glyphicon-pencil" aria-hidden="true" ></span>Edit</button></a></td>
						<td><a href="{% url 'blog:delete_post' slug=post.slug %}"><button type="button" class="btn btn-danger"><span class="glyphicon glyphicon-trash" aria-hidden="true" ></span>Delete</button></a></td>
					</tr>
				
				
			{% endfor %}
		</table>
		{% include 'blog/paginator.html' with page=posts %}
	</div>


{% endblock %}

cms/blog/templates/blog/backend/new_post.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-sm-8 blog-main">
	<h1>New Post</h1>
	<form method="POST" class="post-form">
		{% csrf_token %}
		{{ form | crispy }}
		<button type="submit" class="btn btn-success">Save</button>
	</form>
</div>
{% endblock %}

cms/blog/templates/blog/base.html
{% load static %}
{% load admin_urls %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="author" content="">
      <title>{% block title %}{% endblock %}</title>
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">  
      <script type="text/javascript" src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

      <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
      <![endif]-->

  </head>

  <body>

    <div class="blog-masthead">

      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url 'blog:list_of_posts' %}">Home</a>
          <a class="blog-nav-item" href="{% url 'blog:new_post' %}">New Post</a>
          <a class="blog-nav-item" href="{% url 'blog:list_of_posts_backend' %}">Backend Access</a>
          <a class="blog-nav-item" href='{% url "admin:index" %}'>Admin Access</a>


        </nav>
      </div>
    </div>


	  


    <div class="container">
 

      <div class="row">
        {% include 'blog/messages.html' %}
        {% block content %}
    	    
    	  {% endblock %}

        {% block sidebar %}
   
        {% endblock %}



      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>&copy; Copyright 2018 <a href="http://affroapps.com">affroapps</a> .</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

  </body>
</html>

cms/blog/templates/blog/category/list_of_posts_by_category.html
{% extends 'blog/base.html' %}

{% block title %} {{ category.name }} {% endblock %}

{% block content %}
<div class="col-sm-8 blog-main">
	<h1>{{ category.name }}</h1>
	{% for posts in post %}
		<h2><a href="{{ posts.get_absolute_url }}">{{ posts.title }}</a></h2>
		<p>Written by {{ posts.author }} on {{ posts.published }}</p>
		<hr>
		{{ posts.content | truncatewords:40 | linebreaks }}
	{% endfor %}
</div>
{% endblock %}

cms/blog/templates/blog/messages.html
{% if messages %}
	{% for message in messages %}
	{% if message.tags %} <div class="alert alert-{{message.tags}}">{{ message }}</div>{% endif %}
	{% endfor %}
{% endif %}

cms/blog/templates/blog/paginator.html
<nav arial-label = "Page navigation">
	{% if page.has_other_pages %}
		<ul class="pagination">
			{% if page.has_previous %}
				<li>
					<a aria-label="Previous" href="?page={{page.previous_page_number}}">&laquo;</a>
				</li>
			{% else %}
				<li class="disabled"><span>&laquo;</span></li>
			{% endif %}
			{% for pages in page.paginator.page_range %}
				{% if page.number == pages %}
					<li class="active"><span>{{ pages }}<span class="sr-only">( current )</span></span></li>
				{% else %}
					<li><a href="?page={{pages}}">{{ pages }}</a></li>
				{% endif %}
			{% endfor %}
			{% if page.has_next %}
				<li><a href="?page={{page.nex_page_number}}">&raquo;</a></li>
			{% else %}
				<li class="disabled"><span>&raquo;</span></li>
			{% endif %}
		</ul>
	{% endif %}
</nav>

cms/blog/templates/blog/post/add_comment.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col-sm-8 blog-main">
	<h1>Add New Comment</h1>
	<form method="POST" >{% csrf_token %}
		{{ form | crispy }}
		<button type="submit" class="btn btn-success">Submit</button>
	</form>
</div>
{% endblock %}
{% block sidebar %}
    {% include 'blog/sidebar.html' %}
{% endblock %}

cms/blog/templates/blog/post/list_of_posts.html
{% extends 'blog/base.html' %}

{% block description %} This is a caterory {% endblock %}
{% block title %} {{ category.name }} {% endblock %}

{% block content %}
<div class="col-sm-8 blog-main">
		{% for post in posts %}
		<div class="blog-post">
            <h2 class="blog-post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p class="blog-post-meta">{{ post.published }} by <a href="#">{{ post.author }}</a> in <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></p>

            <p>{{ post.content | truncatewords:40 | linebreaks }}</p>

      	</div><!-- /.blog-post -->
      	{% endfor %}

        {% include 'blog/paginator.html' with page=posts %}

      <!-- <nav>
        <ul class="pager">
          <li><a href="#">Previous</a></li>
          <li><a href="#">Next</a></li>
        </ul>
      </nav> -->
</div><!-- /.blog-main -->
{% endblock %}

{% block sidebar %}
    {% include 'blog/sidebar.html' %}
{% endblock %}

cms/blog/templates/blog/post/post_detail.html
{% extends 'blog/base.html' %}

{% block description %} {{ post.seo_description }} {% endblock %}
{% block title %} {{ category.name }} {% endblock %}

{% block content %}
<div class="col-sm-8 blog-main">
<h2>{{ post.title }}</h2>
		<p><small>Written by {{ post.author }} on {{ post.published }} in 
			<a href="{{post.category.get_absolute_url}}">{{ post.category }}</a></small></p>
		<hr>
		{{ post.content | linebreaks }}
		<hr>
		<p>{{ post.comments.count }} Comment(s)</p>
		<p class="text-center">
			<button type="button" class="btn btn-default">
			<a href="{% url 'blog:add_comment' slug=post.slug %}">Leave a comment</a></button></p>
		<h1>Leave a comment <small></small></h1>
		{% for comment in post.comments.all %}
			<div class="panel panel-default">
				<div class="panel-heading">			
					<p>{{ comment.user }} commented on {{ comment.created }}</p>
				</div>
			

				<p class="btn btn-alert">{{ comment.body }}</p>
			</div>
			<hr>
		{% empty %}
		<p>No comments so far</p>
		{% endfor %}
</div><!-- /.blog-main -->
{% endblock %}
{% block sidebar %}
    {% include 'blog/sidebar.html' %}
{% endblock %}

cms/blog/templates/blog/post/post_preview.html
{% extends 'blog/base.html' %}

{% block description %} {{ post.seo_description }} {% endblock %}
{% block title %} {{ category.name }} {% endblock %}

{% block content %}
<div class="col-sm-8 blog-main">
	<div class="alert alert-danger" role="alert">This post is currently a Preview, set staus to published to publish the post</div>
<h2>{{ post.title }}</h2>
		<p><small>Written by {{ post.author }} on {{ post.published }} in 
			<a href="{{post.category.get_absolute_url}}">{{ post.category }}</a></small></p>
		<hr>
		{{ post.content | linebreaks }}
		<hr>
		<p>{{ post.comments.count }} Comment(s)</p>
		<p class="text-center">
			<button type="button" class="btn btn-default">
			<a href="{% url 'blog:add_comment' slug=post.slug %}">Leave a comment</a></button></p>
		<h1>Leave a comment <small></small></h1>
		{% for comment in post.comments.all %}
			<div class="panel panel-default">
				<div class="panel-heading">			
					<p>{{ comment.user }} commented on {{ comment.created }}</p>
				</div>
			

				<p class="btn btn-alert">{{ comment.body }}</p>
			</div>
			<hr>
		{% empty %}
		<p>No comments so far</p>
		{% endfor %}
</div><!-- /.blog-main -->
{% endblock %}
{% block sidebar %}
    {% include 'blog/sidebar.html' %}
{% endblock %}

cms/blog/templates/blog/sidebar.html
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div>
          <div class="sidebar-module">
            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
              <li><a href="#">February 2014</a></li>
              <li><a href="#">January 2014</a></li>
              <li><a href="#">December 2013</a></li>
              <li><a href="#">November 2013</a></li>
              <li><a href="#">October 2013</a></li>
              <li><a href="#">September 2013</a></li>
              <li><a href="#">August 2013</a></li>
              <li><a href="#">July 2013</a></li>
              <li><a href="#">June 2013</a></li>
              <li><a href="#">May 2013</a></li>
              <li><a href="#">April 2013</a></li>
            </ol>
          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </div> --><!-- /.blog-sidebar